set(PACKS_REPO "C:/Program Files (x86)/Atmel/Studio/7.0/packs")

set(ASF_SOURCES
    src/ASF/common/boards/board.h
    src/ASF/common/boards/user_board/init.c
    src/ASF/common/boards/user_board/user_board.h
    src/ASF/common/services/clock/genclk.h
    src/ASF/common/services/clock/osc.h
    src/ASF/common/services/clock/pll.h
    src/ASF/common/services/clock/sam4e/genclk.h
    src/ASF/common/services/clock/sam4e/osc.h
    src/ASF/common/services/clock/sam4e/pll.h
    src/ASF/common/services/clock/sam4e/sysclk.c
    src/ASF/common/services/clock/sam4e/sysclk.h
    src/ASF/common/services/clock/sysclk.h
    src/ASF/common/services/delay/delay.h
    src/ASF/common/services/delay/sam/cycle_counter.c
    src/ASF/common/services/delay/sam/cycle_counter.h
    src/ASF/common/services/spi/sam_spi/spi_master.c
    src/ASF/common/services/spi/sam_spi/spi_master.h
    src/ASF/common/services/spi/spi_master.h
    src/ASF/common/services/twi/sam_twi/twi_master.h
    src/ASF/common/services/twi/sam_twi/twi_slave.h
    src/ASF/common/services/twi/twi_master.h
    src/ASF/common/services/twi/twi_slave.h
    src/ASF/common/utils/interrupt/interrupt_sam_nvic.c
    src/ASF/common/utils/interrupt/interrupt_sam_nvic.h
    src/ASF/common/utils/interrupt.h
    src/ASF/common/utils/parts.h
    src/ASF/sam/drivers/dacc/dacc.c
    src/ASF/sam/drivers/dacc/dacc.h
    src/ASF/sam/drivers/efc/efc.c
    src/ASF/sam/drivers/efc/efc.h
    src/ASF/sam/drivers/pdc/pdc.c
    src/ASF/sam/drivers/pdc/pdc.h
    src/ASF/sam/drivers/pdc/pdc_uart_example/pdc_uart_example.h
    src/ASF/sam/drivers/pio/pio.c
    src/ASF/sam/drivers/pio/pio.h
    src/ASF/sam/drivers/pio/pio_handler.c
    src/ASF/sam/drivers/pio/pio_handler.h
    src/ASF/sam/drivers/pmc/pmc.c
    src/ASF/sam/drivers/pmc/pmc.h
    src/ASF/sam/drivers/pmc/sleep.c
    src/ASF/sam/drivers/pmc/sleep.h
    src/ASF/sam/drivers/spi/spi.c
    src/ASF/sam/drivers/spi/spi.h
    src/ASF/sam/drivers/tc/tc.c
    src/ASF/sam/drivers/tc/tc.h
    src/ASF/sam/drivers/tc/tc_capture_waveform_example/tc_capture_waveform_example.h
    src/ASF/sam/drivers/twi/twi.c
    src/ASF/sam/drivers/twi/twi.h
    src/ASF/sam/drivers/wdt/wdt.c
    src/ASF/sam/drivers/wdt/wdt.h
    src/ASF/sam/services/flash_efc/flash_efc.c
    src/ASF/sam/services/flash_efc/flash_efc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/acc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/aes.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/afec.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/can.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/chipid.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/cmcc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/dacc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/dmac.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/efc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/gmac.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/gpbr.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/hsmci.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/matrix.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/pdc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/pio.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/pmc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/pwm.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/rstc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/rswdt.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/rtc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/rtt.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/smc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/spi.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/supc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/tc.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/twi.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/uart.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/udp.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/usart.h
    src/ASF/sam/utils/cmsis/sam4e/include/component/wdt.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/acc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/aes.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/afec0.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/afec1.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/can0.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/can1.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/chipid.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/cmcc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/dacc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/dmac.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/efc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/gmac.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/gpbr.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/hsmci.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/matrix.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/pioa.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/piob.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/pioc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/piod.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/pioe.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/pmc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/pwm.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/rstc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/rswdt.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/rtc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/rtt.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/smc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/spi.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/supc.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/tc0.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/tc1.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/tc2.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/twi0.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/twi1.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/uart0.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/uart1.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/udp.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/usart0.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/usart1.h
    src/ASF/sam/utils/cmsis/sam4e/include/instance/wdt.h
    src/ASF/sam/utils/cmsis/sam4e/include/pio/sam4e16c.h
    src/ASF/sam/utils/cmsis/sam4e/include/pio/sam4e16cb.h
    src/ASF/sam/utils/cmsis/sam4e/include/pio/sam4e16e.h
    src/ASF/sam/utils/cmsis/sam4e/include/pio/sam4e8c.h
    src/ASF/sam/utils/cmsis/sam4e/include/pio/sam4e8cb.h
    src/ASF/sam/utils/cmsis/sam4e/include/pio/sam4e8e.h
    src/ASF/sam/utils/cmsis/sam4e/include/sam4e.h
    src/ASF/sam/utils/cmsis/sam4e/include/sam4e16c.h
    src/ASF/sam/utils/cmsis/sam4e/include/sam4e16cb.h
    src/ASF/sam/utils/cmsis/sam4e/include/sam4e16e.h
    src/ASF/sam/utils/cmsis/sam4e/include/sam4e8c.h
    src/ASF/sam/utils/cmsis/sam4e/include/sam4e8cb.h
    src/ASF/sam/utils/cmsis/sam4e/include/sam4e8e.h
    src/ASF/sam/utils/cmsis/sam4e/source/templates/exceptions.c
    src/ASF/sam/utils/cmsis/sam4e/source/templates/exceptions.h
    src/ASF/sam/utils/cmsis/sam4e/source/templates/gcc/startup_sam4e.c
    src/ASF/sam/utils/cmsis/sam4e/source/templates/system_sam4e.c
    src/ASF/sam/utils/cmsis/sam4e/source/templates/system_sam4e.h
    src/ASF/sam/utils/compiler.h
    src/ASF/sam/utils/fpu/fpu.h
    src/ASF/sam/utils/header_files/io.h
    src/ASF/sam/utils/preprocessor/mrepeat.h
    src/ASF/sam/utils/preprocessor/preprocessor.h
    src/ASF/sam/utils/preprocessor/stringz.h
    src/ASF/sam/utils/preprocessor/tpaste.h
    src/ASF/sam/utils/status_codes.h
    src/ASF/sam/utils/syscalls/gcc/syscalls.c
    src/ASF/thirdparty/CMSIS/Include/arm_common_tables.h
    src/ASF/thirdparty/CMSIS/Include/arm_const_structs.h
    src/ASF/thirdparty/CMSIS/Include/arm_math.h
    src/ASF/thirdparty/CMSIS/Include/cmsis_compiler.h
    src/ASF/thirdparty/CMSIS/Include/cmsis_gcc.h
    src/ASF/thirdparty/CMSIS/Include/cmsis_version.h
    src/ASF/thirdparty/CMSIS/Include/core_cm4.h
    src/ASF/thirdparty/CMSIS/Include/mpu_armv7.h
    src/asf.h
    src/config/conf_board.h
    src/config/conf_clock.h
    src/config/conf_spi_master.h
    )

set(ASF_INCLUDE_DIRECTORIES
    src
    src/ASF
    src/ASF/common
    src/ASF/common/boards
    src/ASF/common/boards/user_board
    src/ASF/common/services
    src/ASF/common/services/clock
    src/ASF/common/services/clock/sam4e
    src/ASF/common/services/delay
    src/ASF/common/services/delay/sam
    src/ASF/common/services/spi
    src/ASF/common/services/spi/sam_spi
    src/ASF/common/services/twi
    src/ASF/common/services/twi/sam_twi
    src/ASF/common/utils
    src/ASF/common/utils/interrupt
    src/ASF/sam
    src/ASF/sam/drivers
    src/ASF/sam/drivers/dacc
    src/ASF/sam/drivers/efc
    src/ASF/sam/drivers/pdc
    src/ASF/sam/drivers/pdc/pdc_uart_example
    src/ASF/sam/drivers/pio
    src/ASF/sam/drivers/pmc
    src/ASF/sam/drivers/spi
    src/ASF/sam/drivers/tc
    src/ASF/sam/drivers/tc/tc_capture_waveform_example
    src/ASF/sam/drivers/twi
    src/ASF/sam/drivers/wdt
    src/ASF/sam/services
    src/ASF/sam/services/flash_efc
    src/ASF/sam/utils
    src/ASF/sam/utils/cmsis
    src/ASF/sam/utils/cmsis/sam4e
    src/ASF/sam/utils/cmsis/sam4e/include
    src/ASF/sam/utils/cmsis/sam4e/include/component
    src/ASF/sam/utils/cmsis/sam4e/include/instance
    src/ASF/sam/utils/cmsis/sam4e/include/pio
    src/ASF/sam/utils/cmsis/sam4e/source
    src/ASF/sam/utils/cmsis/sam4e/source/templates
    src/ASF/sam/utils/cmsis/sam4e/source/templates/gcc
    src/ASF/sam/utils/fpu
    src/ASF/sam/utils/header_files
    src/ASF/sam/utils/linker_scripts
    src/ASF/sam/utils/linker_scripts/sam4e
    src/ASF/sam/utils/linker_scripts/sam4e/sam4e8
    src/ASF/sam/utils/linker_scripts/sam4e/sam4e8/gcc
    src/ASF/sam/utils/make
    src/ASF/sam/utils/preprocessor
    src/ASF/sam/utils/syscalls
    src/ASF/sam/utils/syscalls/gcc
    src/ASF/thirdparty
    src/ASF/thirdparty/CMSIS
    src/ASF/thirdparty/CMSIS/Include
    src/ASF/thirdparty/CMSIS/Lib
    src/ASF/thirdparty/CMSIS/Lib/GCC
    src/config
    )

set(FREERTOS_SOURCES
    src/ASF/thirdparty/FreeRTOS/croutine.c
    src/ASF/thirdparty/FreeRTOS/event_groups.c
    src/ASF/thirdparty/FreeRTOS/FreeRTOSConfig.h
    src/ASF/thirdparty/FreeRTOS/include/atomic.h
    src/ASF/thirdparty/FreeRTOS/include/croutine.h
    src/ASF/thirdparty/FreeRTOS/include/deprecated_definitions.h
    src/ASF/thirdparty/FreeRTOS/include/event_groups.h
    src/ASF/thirdparty/FreeRTOS/include/FreeRTOS.h
    src/ASF/thirdparty/FreeRTOS/include/list.h
    src/ASF/thirdparty/FreeRTOS/include/message_buffer.h
    src/ASF/thirdparty/FreeRTOS/include/mpu_prototypes.h
    src/ASF/thirdparty/FreeRTOS/include/mpu_wrappers.h
    src/ASF/thirdparty/FreeRTOS/include/portable.h
    src/ASF/thirdparty/FreeRTOS/include/projdefs.h
    src/ASF/thirdparty/FreeRTOS/include/queue.h
    src/ASF/thirdparty/FreeRTOS/include/semphr.h
    src/ASF/thirdparty/FreeRTOS/include/StackMacros.h
    src/ASF/thirdparty/FreeRTOS/include/stack_macros.h
    src/ASF/thirdparty/FreeRTOS/include/stream_buffer.h
    src/ASF/thirdparty/FreeRTOS/include/task.h
    src/ASF/thirdparty/FreeRTOS/include/timers.h
    src/ASF/thirdparty/FreeRTOS/list.c
    src/ASF/thirdparty/FreeRTOS/portable/GCC/ARM_CM3/port.c
    src/ASF/thirdparty/FreeRTOS/portable/GCC/ARM_CM3/portmacro.h
    src/ASF/thirdparty/FreeRTOS/portable/MemMang/heap_4.c
    src/ASF/thirdparty/FreeRTOS/queue.c
    src/ASF/thirdparty/FreeRTOS/stream_buffer.c
    src/ASF/thirdparty/FreeRTOS/tasks.c
    src/ASF/thirdparty/FreeRTOS/timers.c
    )

set(FREERTOS_INCLUDE_DIRS
    src/ASF/thirdparty/FreeRTOS
    src/ASF/thirdparty/FreeRTOS/include
    src/ASF/thirdparty/FreeRTOS/portable
    src/ASF/thirdparty/FreeRTOS/portable/GCC
    src/ASF/thirdparty/FreeRTOS/portable/GCC/ARM_CM3
    src/ASF/thirdparty/FreeRTOS/portable/MemMang
    )