set(SOURCES
    display_data_sender.c
    display_data_sender.h
    DSP_functions.c
    DSP_functions.h
    external_periph_ctrl.c
    external_periph_ctrl.h
    ILI9486_config.h
    ILI9486_ctrl.c
    ILI9486_fonts.h
    ILI9486_private.h
    ILI9486_public.h
    keyboard.c
    keyboard.h
    LCD1608.c
    LCD1608.h
    MCP23016.c
    MCP23016.h
    MCP3462.c
    MCP3462.h
    menu.c
    menu.h
    menu_calibration.c
    menu_calibration.h
    menu_ili9486.c
    menu_ili9486.h
    menu_ili9486_kbrd_mngr.c
    menu_ili9486_kbrd_mngr.h
    menu_types_ili9486.h
    signal_conditioning.c
    signal_conditioning.h
    system.c
    system.h
    system_init.c
    system_init.h
    twi_pdc.c
    twi_pdc.h
    )