set(SOURCES
    system.c
    system.h
    system_init.c
    system_init.h
    MCP23016.c
    MCP23016.h
    twi_pdc.c
    twi_pdc.h
    keyboard.c
    keyboard.h
    LCD1608.c
    LCD1608.h
    ILI9486_config.h
    external_periph_ctrl.c
    external_periph_ctrl.h
    signal_conditioning.c
    signal_conditioning.h
    )